DjangoProject/music_rentals/music/urls.py
from django.conf.urls import url
# Doctring
from . import views

app_name = 'music'

urlpatterns = [
				# /music/
				url(r'^$', views.IndexView.as_view(), name='index'),

				# /music/712/
				url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

				#/music/album/add/
				url(r'album/add$', views.AlbumCreate.as_view(), name='album-add'),

				#/music/album/2/
				url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

				#/music/album/2/delete/
				url(r'(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

DjangoProject/music_rentals/music_rentals/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^music/', include('music.urls')),
	url(r'^inventory/', include('music.urls')),
]

DjangoProject/music_rentals/music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
	artist = models.CharField(max_length=100)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=50)
	album_logo = models.URLField()
	album_total = models.FloatField(default=0)
	release_year = models.IntegerField(default=0)
	quantity = models.IntegerField(default=1)

	def get_absolute_url(self):
			return reverse('music:detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=100)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

DjangoProject/music_rentals/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album


class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

DjangoProject/music_rentals/music/templates/music/album_form.html
{% extends 'music/base.html' %} 
{% block title %}Add a New Album{% endblock %} 
{% block albums_active %}active{% endblock %} 

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

DjangoProject/music_rentals/music/templates/music/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Main Page | MiTunes Music{% endblock %}</title>
    {% load staticfiles%}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat+Brush" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css'  %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Logo -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
                <a class="navbar-brand" href="{% url 'music:index' %}"><span class="glyphicon glyphicon-equalizer"></span>MiTunes Music Rentals</a>
            </div>
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search For Album</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album To Inventory
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %} {% endblock %}
</body>

</html>

DjangoProject/music_rentals/music/templates/music/detail.html
{% extends 'music/base.html' %} {% block body %}
<title>{% block title %}Album Details | MiTunes Music{% endblock %}</title>
<div class="container-fluid songs-container">
    <div class="row">
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body" style="margin-top: 0;">
                    <a href="{% url 'music:detail' album.id %}">
                        <img src="{{ album.album_logo }}" class="img-responsive">
                    </a>

                    <h1 id="google">{{ album.album_title }}
                        <small id="google">{{ album.genre }}</small>
                    </h1>
                    <h2 id="google">{{ album.artist }}</h2>
                    <small style="font-size: 15px;" id="google">Released in {{ album.release_year }}</small>
                    <div class="slider-vertical"></div>
                    <div id="purhcaseForm">
                        <form id="purchase">
                            <br id="google"> Item Price: ${{ album.album_total }}
                            <input type='button' name='subtract' class="btn btn-danger" onclick='Total("qty",-1,"total",{{ album.album_total }});' value='-' />
                            <input type='button' name='add' class="btn btn-success" onclick='Total("qty",1,"total", {{ album.album_total }});' value='+' />
                            <h2 id="google">Quantity</h2><input class="roboto" type='text' name='qty' id='qty' readonly=true value="0" />
                            <h2 id="google">Total Price w/ sales tax:</h2><input class="roboto" type='text' name='total' id='total' value="0" />
                        </form>
                    </div>
                    <br>
                    <center><button type="submit" class="btn btn-primary">Rent This Album</button></center>

                </div>
            </div>
            <script>
                function Total(qty, ud, total, value) {
                    qty = document.getElementById(qty);
                    ud > 0 ? qty.value++ : qty.value--;
                    qty.value = Math.max(qty.value, 0);
                    document.getElementById(total).value = qty.value * value;
                }
            </script>
            </head>

            <body>
        </div>


        {% for song in album.song_set.all %} {{ song.song_title }} {% if song.is_favorite %}
        <img src="http://icons.iconarchive.com/icons/aha-soft/multimedia/16/favourites-star-SH-icon.png"> {% endif %}
        <br> {% endfor %} {% endblock %}

DjangoProject/music_rentals/music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

DjangoProject/music_rentals/music/templates/music/index.html
 {% extends 'music/base.html' %} {% block body %} {% if all_albums %} {% if album_total % }
<div class="jumbotron">
    <center>
        <h1 class="google_font">Welcome To MiTunes Music Rentals 2.0</h1>
        <p class="google_font">Don't Hesitate, Just Appreciate!</p>
        <p class="google_font">Take Your Time And BROWSE!!</p>
        <p class="google_font">More Responsive, More Understandable, More Music!</p>
        <p><a class="btn btn-primary btn-lg" href="#albums" role="button">What's At The Bottom?</a></p>
    </center>
</div>

<div class="container-fluid songs-container">
    <div class="row" id="albums">
        {% for album in all_albums %}
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        <img src="{{ album.album_logo }}" class="img-responsive">
                    </a>
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h4>{{ album.artist }}</h4>
                        <a href="{% url 'music:detail' album.id %}" class="btn btn-primary">Album Details</a>
                        <button class="btn btn-default"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></button>
                        <button class="btn btn-default"><span class="glyphicon glyphicon-thumbs-up"></span></button>
                        <button class="btn btn-default"><span class="glyphicon glyphicon-trash"></span></button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<h3>You don't have any albums</h3>
{% endif %} {% endblock %}

DjangoProject/music_rentals/music/templates/music/inventory.html
{% extends 'music/base.html' %} {% block body %}